theme: jekyll-theme-cayman
title: Cuisine Interactive Shiny
description: Interactive web app implemented in Shiny.
github:
  home_url: https://bonioloff.github.io/
  demo_url: https://bonioloff.shinyapps.io/cuisine_interactive_shiny/
