theme: jekyll-theme-cayman
title: Cuisine Interactive Shiny
description: Interactive web app implemented in Shiny.
github:
  Home: https://github.com/BoniOloff
  LinkedIn: https://www.linkedin.com/in/bonioloff
